-- User
INSERT INTO USER (ID, EMAIL, USERNAME, PASSWORD, AUTHKEY) VALUES ('initId', 'initEmail@localhost', 'initUsername', 'initPassword', 'initAuthKey');
INSERT INTO USER (ID, EMAIL, USERNAME, PASSWORD, AUTHKEY) VALUES ('ui', 'u@localhost', 'un', 'up', 'ua');
INSERT INTO USER (ID, EMAIL, USERNAME, PASSWORD, AUTHKEY) VALUES ('x', 'x@localhost', 'x', 'x', 'x');
INSERT INTO USER (ID, EMAIL, USERNAME, PASSWORD, AUTHKEY) VALUES ('a', 'a@localhost', NULL, NULL, 'ak');
INSERT INTO USER (ID, EMAIL, USERNAME, PASSWORD, AUTHKEY) VALUES ('b', 'b@localhost', NULL, NULL, 'bk');
INSERT INTO USER (ID, EMAIL, USERNAME, PASSWORD, AUTHKEY) VALUES ('c', 'c@localhost', NULL, NULL, 'ck');

-- Termine
INSERT INTO TERMINPLAN (ID, SUMMARY, DATE, USER_ID) VALUES ('tpId', 'tpSum', NOW(), 'x');
INSERT INTO TERMINPLAN (ID, SUMMARY, DATE, USER_ID) VALUES ('tpId2', 'tpSum2', NOW(), 'ui');
INSERT INTO TERMINPLAN (ID, SUMMARY, DATE, USER_ID) VALUES ('tpId3', 'tpSum3', NOW(), 'x');

INSERT INTO INVITATION (ID, USER_ID, ANSWER, TERMIN_ID) VALUES ('i1', 'a', null, 'tpId');
INSERT INTO INVITATION (ID, USER_ID, ANSWER, TERMIN_ID) VALUES ('i2', 'b', 'YES', 'tpId');
INSERT INTO INVITATION (ID, USER_ID, ANSWER, TERMIN_ID) VALUES ('i3', 'c', 'NO', 'tpId');